import type { Config } from 'tailwindcss'
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // shadcn/ui tokens (kept for component compat)
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // New design-system semantic tokens
        'surface': '#0c1324',
        'surface-dim': '#0c1324',
        'surface-bright': '#33394c',
        'surface-container-lowest': '#070d1f',
        'surface-container-low': '#151b2d',
        'surface-container': '#191f31',
        'surface-container-high': '#23293c',
        'surface-container-highest': '#2e3447',
        'on-surface': '#dce1fb',
        'on-surface-variant': '#c7c4d7',
        'inverse-surface': '#dce1fb',
        'inverse-on-surface': '#2a3043',
        'outline': '#908fa0',
        'outline-variant': '#464554',
        'surface-tint': '#c0c1ff',
        'on-primary-token': '#1000a9',
        'primary-container-token': '#8083ff',
        'on-primary-container': '#0d0096',
        'inverse-primary': '#494bd6',
        'secondary-token': '#ddb7ff',
        'on-secondary': '#490080',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        'tertiary': '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#ca8100',
        'on-tertiary-container': '#3e2400',
        'error-token': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'surface-variant': '#2e3447',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontSize: {
        'headline-lg':        ['32px', { lineHeight: '40px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md':        ['20px', { lineHeight: '28px',  fontWeight: '600' }],
        'body-lg':            ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '20px',  fontWeight: '400' }],
        'label-caps':         ['12px', { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '700' }],
        'mono-stat':          ['18px', { lineHeight: '24px',  letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config
